#!/bin/sh -e

mkdir -p "$1/bin"

# Install kiss utilities.
cp -f kiss contrib/* "$1/bin/"

# Install distribution documentation.
for doc in docs/site/*.txt; do
    install -Dm644 "$doc" "$1/share/doc/kiss/${doc##*/}"
done

# Install the Wiki.
cp -r wiki "$1/share/doc/kiss/wiki"

# Remove unnecessary pages.
rm -f "$1/share/doc/kiss/wiki/README.txt" \
      "$1/share/doc/kiss/news.txt" \
      "$1/share/doc/kiss/blog.txt" \
      "$1/share/doc/kiss/screenshots.txt"
