#!/bin/sh -e
LDFLAGS="-static" \
./configure \
    -C \
    --prefix=/ \
    --disable-nls \
    --with-pic \
    --enable-shared \
    --enable-static

make 
make DESTDIR="$1" CFLAGS="-static" install

