#!/bin/sh -e
./configure --help
LDFLAGS="-static" \
./configure \
    -C \
    --prefix=/ \
    --disable-nls \
    --with-pic \
    --enable-shared \
    --enable-static

make 
make DESTDIR="$1"  install

